version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: aplikasiweb_php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '23778:80'

  mariadb:
    image: mariadb:10.3
    container_name: aplikasiweb_mariadb
    volumes:
      # - ./docker/dbdata:/var/lib/mysql
      - apps_persistent:/var/lib/mysql
    ports:
      - 23776:3306
    restart: always
    environment:
      - TZ=Asia/Jakarta
      # - MYSQL_USER=apps_data
      # - MYSQL_PASSWORD=pass_apps_data
      - MYSQL_ROOT_PASSWORD=admin1
      - MYSQL_DATABASE=aplikasi_web
      
volumes:
  apps_persistent:
